### ISSUE TITLE
Support dynamic `params` on the `Bodyguard.Plug.Authorize` plug

### ISSUE THREAD

**Issue by schrockwell** [schrockwell/bodyguard#47]
On the `Bodyguard.Plug.Authorize` plug, the `action` and `user` options accept functions. We should do that for `params`, too.

**Comment by jung-hunsoo** [comment]
Indeed.

**Comment by albertchan** [comment]
I second this! Any hint on when this may be supported? Thanks!

**Comment by ckreiling** [comment]
Hello, any updates on this? I'd really like this functionality.

**Comment by ckreiling** [comment]
@mmcall10 I see you have a PR open with support for this, how's it going?

**Comment by mmccall10** [comment]
@ckreiling I don't thinks it's been looked at. I haven't heard any feedback on the PR. It's not a very big change. Take a look. I'm pretty sure it won't be supported because there was a work around discussed in chat. I haven't used it in a while and don't find myself in elixir projects anymore.

I think the workaround was something like this:

```elixir
# controller.ex
plug Bodyguard.Plug.Authorize,
    policy: MyApp.Policy,
    action: :access_resource,
    user: &MyApp.BodyguardProvider.get_current_user_and_params/1,
    fallback: MyAppWeb.FallbackController
```

```elixir
# bodyguard_provider.ex
defmodule MyApp.BodyguardProvider do
  def get_current_user_and_params(conn) do
    %{user: conn.assigns.current_user, params: conn.params}
  end

  def get_current_user(conn) do
    conn.assigns.current_user
  end
end
```

```elixir
# policy.ex
def authorize(:access_resource, %{user: %User{id: user_id}, params: %{"resource_id" => resource_id}}, _) do
  // yay or nay
end

def authorize(:access_resource, %User{id: user_id}, %{"resource_id" => resource_id}) do
  // yay or nay
end

def authorize(_, _, _), do: {:error, :unauthorized}
```

Hope that helps.
