### ISSUE TITLE
Support for strong parameters?

### ISSUE THREAD

**Issue by rjurado01** [schrockwell/bodyguard#61]
Is in your plans add support for strong parameters as [Pundit for Rails](https://github.com/varvet/pundit#strong-parameters) ?

**Comment by baldwindavid** [comment]
Since params are generally filtered via changesets in Phoenix, it would likely need to work alongside them. You're not really asking _how_ to do this without explicit support, but perhaps it helps to mention a couple ways to do it even without a Bodyguard method.

Supposing you had a `Projects` context, it could have an authorize rule for `:update_all_attrs`.

Then in your schema (`project.ex`) there could be a custom changeset that takes a user and filters the attributes based upon checking the Bodyguard permission for `:update_all_attrs`.

```elixir
def changeset_for_user(project, attrs, user) do
  permitted_attrs =
    if Bodyguard.permit?(Projects, :update_all_attrs, user, project),
      do: [:name, :description],
      else: [:description]

  project |> cast(attrs, permitted_attrs)
end
```

Your `update_project` method in the `Projects` context could pass in the user and run it through the filtered changeset.

```elixir
def update_project(project, attrs, user) do
  project |> Project.changeset_for_user(attrs, user) |> Repo.update()
end
```

Another way to do it would be to have multiple well-named changesets that filter different attributes and do the Bodyguard check in the context in `update_project` to select the appropriate changeset.

**Comment by schrockwell** [comment]
Thanks for the feedback, but this is out-of-scope for Bodyguard and won't be implemented.
