### ISSUE TITLE
Anonymous Function Example Broken?

### ISSUE THREAD

**Issue by jherdman** [schrockwell/bodyguard#67]
Given...

```elixir
  plug Bodyguard.Plug.Authorize,
    policy: Subscriptions,
    action: :crud,
    user: {UserAuth, :current_user},
    params: & &1.assigns.subscription,
    fallback: MyApp.FallbackController
```

The following error results:

```
== Compilation error in file lib/my_app_web/controllers/subscription_controller.ex ==
** (ArgumentError) cannot escape #Function<0.125979929/1 in :elixir_compiler_1.__MODULE__/1>. The supported values are: lists, tuples, maps
, atoms, numbers, bitstrings, PIDs and remote functions in the format &Mod.fun/arity
```

This is relevant per https://github.com/schrockwell/bodyguard/blob/develop/README.md#plugs uses this.

Platform:

```
Erlang/OTP 22 [erts-10.7.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.10.3 (compiled with Erlang/OTP 22)
```

**Comment by wodow** [comment]
Can't quote an anoymous function?  ref  https://elixirforum.com/t/quote-ed-expressions-and-functions/15996

**Comment by benkimpel** [comment]
I ran into this issue as well. I believe @wodow is correct as this seems to occur during the Controller.Pipeline macro expansion/plug build. It may have worked as documented with previous versions of plug or phoenix although I'm not quite sure how because I'm not familiar with that code.

For a working implementation of params you could define a function in your controller and provide it to the plug as a module/function tuple `params: {__MODULE__, :subscription}` or in the form of `&__MODULE__.subscription/1` where the function's definition is `def subscription(conn), do: conn.assigns.subscription`.

**Comment by benkimpel** [comment]
(function will need to be public)

**Comment by schrockwell** [comment]
Thanks folks. It's really interesting that `& &1.foo.bar` cannot be escaped, but `&MyModule.foo/1` can.

Anyway, I have updated the example in the readme to use the `{module, fun}` notation.
